name: Run FAANG Script

on:
  schedule:
    - cron: '0 9 * * 6'  # Executa todo sábado às 9h UTC
  workflow_dispatch:      # Permite disparo manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Recomendo especificar a versão exata

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib

      - name: Run FAANG script
        run: python faang.py  # Certifique-se de que faang.py está na raiz do repositório


       
 
